server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mybatis?allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
    com:
      rszhang:
        mybatisdemo:
          controller: info
          dao: debug

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
